// Mocks generated by Mockito 5.3.2 from annotations
// in smartx/test/features/splash/presentation/bloc/user_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:smartx/core/error/failures.dart' as _i6;
import 'package:smartx/features/splash/domain/entity/user.dart' as _i8;
import 'package:smartx/features/splash/domain/repository/user_repository.dart'
    as _i2;
import 'package:smartx/features/splash/domain/usecase/cache_user_usecase.dart'
    as _i7;
import 'package:smartx/features/splash/domain/usecase/get_user_usecase.dart'
    as _i9;

import 'user_bloc_test.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserBlocCacheUserUseCaseTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserBlocCacheUserUseCaseTest extends _i1.Mock
    implements _i4.UserBlocCacheUserUseCaseTest {
  MockUserBlocCacheUserUseCaseTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.UserRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(_i7.Params? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
            _FakeEither_1<_i6.Failure, bool>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}

/// A class which mocks [UserBlocGetUserUseCaseTest].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserBlocGetUserUseCaseTest extends _i1.Mock
    implements _i4.UserBlocGetUserUseCaseTest {
  MockUserBlocGetUserUseCaseTest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UserRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeUserRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.UserRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i8.User>> call(
          _i9.WithOutParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, _i8.User>>.value(
            _FakeEither_1<_i6.Failure, _i8.User>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i8.User>>);
}
