name: smartx
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #Service locator
  get_it: ^7.2.0
  #State managment
  flutter_bloc: ^8.1.1
  #Value equality
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  #Functional programing
  dartz: ^0.10.1
  #check network
  internet_connection_checker: ^1.0.0+1
  #Remote API
  http: ^0.13.5
  #Caching
  shared_preferences: ^2.0.17
  cupertino_icons: ^1.0.2
  #fonts
  google_fonts: ^3.0.1
  #responsive sizing
  flutter_screenutil: ^5.6.1
  #navigation
  go_router: ^6.0.3
  #gridview widget
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  #testing
  mockito: ^5.3.2
  #build generate
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  #json issues
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/
